services:
  question_helper:
    class: Symfony\Component\Console\Helper\QuestionHelper
  task_list_command:
    autowire: false
    class: SprykerSdk\Sdk\Presentation\Console\Commands\TaskListCommand
    arguments:
      - '@task_repository'
    tags: ['console.command']
  task_run_command:
    autowire: false
    class: SprykerSdk\Sdk\Presentation\Console\Commands\TaskExecuteCommand
    arguments:
      - '@task_executor'
      - '@local_cli_command_runner'
    tags: ['console.command']
  init_sdk_command:
    autowire: false
    class: SprykerSdk\Sdk\Presentation\Console\Commands\InitSdkCommand
    tags: ['console.command']
    arguments:
      - '@question_helper'
      - '@setting_repository'
      - '@doctrine.database_create_command'
      - '@doctrine_migrations.migrate_command'
      - '@yaml_parser'
      - '%kernel.project_dir%/src/SprykerSdk/Sdk/Settings/settings.yaml'
  init_project_command:
    autowire: false
    class: SprykerSdk\Sdk\Presentation\Console\Commands\InitProjectCommand
    tags: ['console.command']
    arguments:
      - '@question_helper'
      - '@setting_repository'
      - '@yaml_parser'
      - '%project_settings_file%'