version: '3.0'

services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - '8080:80'
        volumes:
            - ./:/data
            - ./infrastructure/web/nginx/default-php-fpm.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - sdk
        restart: always

    sdk:
        container_name: sdk-php
        build:
            context: .
            dockerfile: infrastructure/web/php-fpm.Dockerfile
        volumes:
            - ./:/data
        restart: always
