version: '3.0'

services:
    nginx:
        image: nginx:stable-alpine
        container_name: sdk-nginx
        ports:
            - '8080:80'
        volumes:
            - ./public:/data/public
            - ./infrastructure/web/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm
        restart: always

    php-fpm:
        container_name: sdk-php-fpm
        build:
            context: .
            dockerfile: infrastructure/web/php-fpm.Dockerfile
        volumes:
            - ./:/data
        restart: always
        environment:
            APP_ENV: dev
            APP_DEBUG: true
            TELEMETRY_ENABLED: false
            TELEMETRY_TRANSPORT: file
            TELEMETRY_SERVER_URL: ''
            GITHUB_AUTH_METHOD: http_password
            GITHUB_USERNAME: username
            GITHUB_SECRET: password_or_token
            APPLICATION_ENV:    development

