---
id: "acp:endpoints:create"
short_description: "Create ACP default endpoints."
help: ~
stage: build
version: 0.2.1
command: "php %sdk_dir%/vendor/bin/acp app:default-endpoints:create"
type: !php/const SprykerSdk\SdkContracts\Enum\Task::TYPE_LOCAL_CLI_INTERACTIVE
placeholders:
    - name: "%sdk_dir%"
      value_resolver: SDK_DIR
      optional: true
