---
id: 'validation:php:codestyle'
short_description: 'Check your code by running a static code analysis'
help: ~
stage: build
command: 'php %sdk_dir%/vendor/bin/phpcs --standard=%sdk_dir%/vendor/spryker/code-sniffer/Spryker/ruleset.xml %path%'
type: local_cli
placeholders:
  - name: '%sdk_dir%'
    value_resolver: STATIC
    optional: true
    configuration:
      name: 'sdk_dir'
      description: 'Relative to the installation directory of the SDK or absolute path'
      defaultValue: './'
      type: path
      settingPaths: ['sdk_dir']
  - name: '%project_dir%'
    value_resolver: STATIC
    optional: true
    configuration:
      name: 'project_dir'
      description: 'Absolute path to project directory'
      type: path
      settingPaths: ['project_dir']
  - name: '%path%'
    value_resolver: STATIC
    optional: false
    configuration:
      name: 'path'
      description: 'Absolute path to module directory'
      type: path
      settingPaths: []
