api_v1_index_index:
    path: /api/v1/
    controller: SprykerSdk\Sdk\Presentation\RestApi\Controller\v1\IndexController:index
    methods: GET|POST

api_v1_hello_hello_world:
    path: /api/v1/hello-world
    controller: SprykerSdk\Sdk\Presentation\RestApi\Controller\v1\HelloController:helloWorld
    methods: GET
run_task_controller:
    path: /api/v1/task/{task}
    controller: SprykerSdk\Sdk\Presentation\RestApi\Controller\v1\RunTaskController
    methods: POST
init_sdk_controller:
    path: /api/v1/init
    controller: SprykerSdk\Sdk\Presentation\RestApi\Controller\v1\InitSdkController
    methods: POST
update_sdk_controller:
    path: /api/v1/update
    controller: SprykerSdk\Sdk\Presentation\RestApi\Controller\v1\UpdateSdkController
    methods: POST
