api_v1_index_index:
    path: /api/v1/
    controller: SprykerSdk\Sdk\Presentation\RestApi\Controller\v1\IndexController:index
    methods: GET|POST

api_v1_hello_hello_world:
    path: /api/v1/hello-world
    controller: SprykerSdk\Sdk\Presentation\RestApi\Controller\v1\HelloController:helloWorld
    methods: GET
api_v1_task_runner_controller:
    path: /api/v1/task/{task}
    controller: SprykerSdk\Sdk\Presentation\RestApi\Controller\v1\TaskRunnerController
    methods: POST
api_v1_init_controller:
    path: /api/v1/init
    controller: SprykerSdk\Sdk\Presentation\RestApi\Controller\v1\InitController
    methods: POST
api_v1_update_controller:
    path: /api/v1/update
    controller: SprykerSdk\Sdk\Presentation\RestApi\Controller\v1\UpdateController
    methods: POST
