parameters: ~

services:
    SprykerSdk\Sdk\Presentation\RestApi\Controller\v1\IndexController:
        public: true
    SprykerSdk\Sdk\Presentation\RestApi\Controller\v1\TaskRunnerController:
        class: SprykerSdk\Sdk\Presentation\RestApi\Controller\v1\TaskRunnerController
        public: true
        arguments:
            - "@task_executor"
            - "@context_factory"

    SprykerSdk\Sdk\Presentation\RestApi\Controller\v1\HelloController:
        class: SprykerSdk\Sdk\Presentation\RestApi\Controller\v1\HelloController
        public: true
        arguments:
            - "@rest_api_task_executor"

    symfony.console.application:
        class: Symfony\Bundle\FrameworkBundle\Console\Application
        arguments:
            - '@kernel'

    rest_api_task_executor:
        class: SprykerSdk\Sdk\Presentation\RestApi\Executor\Task\RestApiTaskExecutor
        arguments:
            - '@symfony.console.application'
