parameters: ~

services:
    SprykerSdk\Sdk\Presentation\RestApi\Controller\v1\:
        resource: '../../Controller/v1'
        tags: ['container.service_subscriber', 'controller.service_arguments']
        calls:
            - method: setContainer
              arguments: [ '@service_container' ]

