parameters: ~

services:
    SprykerSdk\Sdk\Presentation\RestApi\Controller\v1\:
        resource: '../../Controller/v1'
        tags: ['container.service_subscriber', 'controller.service_arguments']
        calls:
            - method: setContainer
              arguments: [ '@service_container' ]

    symfony.console.application:
        class: Symfony\Bundle\FrameworkBundle\Console\Application
        arguments:
            - '@kernel'

    SprykerSdk\Sdk\Presentation\RestApi\Executor\Task\RestApiTaskExecutor:
        class: SprykerSdk\Sdk\Presentation\RestApi\Executor\Task\RestApiTaskExecutor
        arguments:
            - '@symfony.console.application'

    SprykerSdk\Sdk\Presentation\RestApi\Adapter\Initializer:
        arguments:
            - '@sdk_initializer.strategy_based_initializer'
            - "@doctrine_migrations.migrate_command"

