services:
  file_finder:
    class: Symfony\Component\Finder\Finder
  event_logger_factory:
    class: SprykerSdk\Sdk\Infrastructure\Service\EventLoggerFactory
    arguments:
      - '@project_setting_repository'
  event_logger:
    class: SprykerSdk\Sdk\Infrastructure\Service\EventLogger
    factory: ['@event_logger_factory', 'createEventLogger']
  setting_repository:
    class: SprykerSdk\Sdk\Infrastructure\Repository\SettingRepository
    arguments:
      - '@doctrine.orm.entity_manager'
  project_setting_repository:
    class: SprykerSdk\Sdk\Infrastructure\Repository\ProjectSettingRepository
    arguments:
      - '@setting_repository'
      - '@yaml_parser'
      - '%project_settings_file%'
  yaml_parser:
    class: Symfony\Component\Yaml\Yaml
  task_repository:
    public: true
    class: SprykerSdk\Sdk\Infrastructure\Repository\TaskYamlRepository
    arguments:
      - '@setting_repository'
      - '@file_finder'
      - '@yaml_parser'
      - !tagged_iterator sdk.task
  process_helper:
    class: Symfony\Component\Console\Helper\ProcessHelper
  local_cli_command_runner:
    public: true
    class: SprykerSdk\Sdk\Infrastructure\Service\LocalCliRunner
    tags: ['command.runner']
    arguments:
      - '@process_helper'
  php__command_runner:
    class: SprykerSdk\Sdk\Infrastructure\Service\PhpCommandRunner
    tags: ['command.runner']
  cli_value_receiver:
    public: true
    class: SprykerSdk\Sdk\Infrastructure\Service\CliValueReceiver
    arguments:
      - '@question_helper'
  value_receiver:
    alias: 'cli_value_receiver'
  value_resolver_registry:
    class: SprykerSdk\Sdk\Infrastructure\Service\ValueResolverRegistry
    arguments:
      - '@setting_repository'
      - '@value_receiver'
      - '%kernel.project_dir%'
